---
- name: Configure Web Server Locally
  hosts: all
  become: yes

  tasks:
    - name: Ensure all packages are up to date
      dnf:
        name: '*'
        state: latest

    - name: Install Git
      dnf:
        name: git
        state: present

    - name: Install Nginx on Amazon Linux 2023
      dnf:
        name: nginx
        state: present

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Clone website repository
      git:
        repo: 'https://github.com/avanti-dvp/site-exemplo-aws.git'
        dest: '/tmp/website'
        clone: yes

    - name: Deploy website files to Nginx document root
      copy:
        src: "/tmp/website/"
        dest: "/usr/share/nginx/html/"
        remote_src: yes
        owner: root
        group: nginx
        mode: '0755'
      notify:
      - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted